@startuml EateryAggregation

title Eatery Aggregation

package "EateryAggregation" {
    class Eatery << (R,red) RootEntity >> {
        eateryId
        eateryName
        eateryDescription
        eateryScore
        eateryLocation
        eateryImages
        businessHours
        category
        RegularHoliday
    }

    class eateryId {
        + value: string
    }

    class eateryName {
        + value: string
    }

    class eateryDescription {
        + value: string
    }

    class eateryLocation {
        + value: string
    }

    class eateryImages {
        + value: number
    }

    class businessHours {
        + value: number
    }

    class category {
        + value: string
    }

    class RegularHoliday {
        + value: string
    }

    Eatery *-down- eateryId
    Eatery *-down- eateryName
    Eatery *-down- eateryDescription
    Eatery *-down- eateryLocation
    Eatery *-down- eateryImages
    Eatery *-down- businessHours
    Eatery *-down- category
    Eatery *-down- RegularHoliday

}

@enduml